library2/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [

    path('', include('library_services.urls')),

    # Django Admin
    path('admin/', admin.site.urls),

    # User management
    path('users_accounts/', include('users_accounts.urls')),
    path('accounts/', include('allauth.urls')),
    
]

library_services/urls.py
from django.urls import path
from django.views.generic import RedirectView

from .views import *

urlpatterns = [
    path('', RedirectView.as_view(pattern_name='book-list'), name='home'),
    path('books', BookListView.as_view(), name='book-list'),
    path('book/<int:pk>', BookDetailView.as_view(), name='book-detail'),
    path('book/<int:pk>/days_this_book_is_not_available_for_cons', DaysBookIsNotAvailableForConsView.as_view()),

    path('withdraw', WithdrawView.as_view(), name='withdraw'),
    path('return', ReturnView.as_view(), name='withdraw'),
    path('enter', EnterStudyHallView.as_view(), name='enter-study-hall'),
    path('exit', ExitStudyHall.as_view(), name='exit-study-hall'),

    path('staff', LibrarianView.as_view(), name="librarian-admin-panel"),
    path('to-withdraw-book-list', ToWithdrawBookListView.as_view(), name="to-withdraw-book-list"),
    path('buy-book', BuyBookView.as_view(), name='buy-book'),
    path('add-book-and-copies', AddBookView.as_view(), name='add-book-and-copies'),
    path('book/<int:pk>/staff', BookStaffDetailView.as_view(), name='book-detail-staff'),

    path('profile/active-loans/', ActiveLoansListView.as_view(), name='active-loans'),
    path('profile/loans-history/', LoansHistoryListView.as_view(), name='loans-history'),
    path('profile/rent-reservations/', RentReservationsListView.as_view(), name='rent-reservations'),
    path('profile/cons-reservations/', ConsultationReservationsListView.as_view(), name='cons-reservations'),
    path('profile/seat-reservation/', SeatReservationView.as_view(), name="seat-reservation"),
    path('profile/download-badge', GenerateBadge.as_view(), name='download-badge'),
]

library_services/models.py
from datetime import timedelta, datetime

from django.core.validators import RegexValidator
from django.db import models
from django.core.validators import MinLengthValidator
from django.urls import reverse

from library2 import settings
from library_services.managers import StudyHallSeatReservationManager, LoanManager, QueueManager


class Book(models.Model):
    IT = 'it'
    EN = 'en'
    DE = 'de'
    ES = 'es'
    LANGUAGE_CHOICES = (
        ('it', 'Italiano'),
        ('en', 'Inglese'),
        ('de', 'Tedesco'),
        ('es', 'Spagnolo')
    )

    cover_img = models.URLField()
    title = models.CharField(max_length=254)
    author = models.CharField(max_length=254)
    publishing_year = models.CharField(
        validators=[
            RegexValidator(
                r'^[1-2]\d{3,3}$',
                'Not a valid year')],
        max_length=4)
    language = models.CharField(
        null=False,
        choices=LANGUAGE_CHOICES,
        max_length=10)
    isbn = models.CharField(
        max_length=13,
        validators=[
            MinLengthValidator(
                limit_value=10)],
        null=False,
        unique=True)

    _first_available_copy_for_rent = None

    def get_absolute_url(self):
        return reverse('book-detail', args=[str(self.id)])

    def has_at_least_one_rent_copy(self):
        if self.copy_set.filter(use_destination=Copy.TO_RENT).count() > 0:
            return True
        return False

    def has_at_least_one_cons_copy(self):
        if self.copy_set.filter(use_destination=Copy.TO_CONSULT).count() > 0:
            return True
        return False

    def has_copy_available_for_rent(self):
        for copy in self.copy_set.all():
            if copy.is_available_for_rent():
                self._first_available_copy_for_rent = copy
                return True
        return False

    def get_rent_copy(self):
        # first_available_copy is set in has_copy_available
        if self.has_copy_available_for_rent():
            return self._first_available_copy_for_rent

    def has_consultation_copy_available_on_date(self, date):
        for copy in self.copy_set.all():
            if copy.is_available_for_consultation_on(date):
                return True
        return False

    def get_consultation_copy_for_date(self, date):
        for copy in self.copy_set.all():
            if copy.is_available_for_consultation_on(date):
                return copy


class QueueOfRentReservations(models.Model):
    """
    (id, user, book) where id as primary key autoincrement serves as "timestamp".
     """
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    book = models.ForeignKey(Book, on_delete=models.CASCADE)

    objects = QueueManager()


class Shelf(models.Model):
    position = models.CharField(max_length=254)
    capacity = models.IntegerField()

    def is_full(self):
        if self.copy_set.all().count() == self.capacity:
            return True
        return False


class Copy(models.Model):
    TO_CONSULT = 'to_consult'
    TO_RENT = 'to_rent'
    USE_DESTINATIONS = (
        (TO_CONSULT, 'Consultazione in sede'),
        (TO_RENT, 'Destinato al prestito')
    )

    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    on_shelf = models.ForeignKey(Shelf, on_delete=models.SET(None))
    use_destination = models.CharField(
        null=False, choices=USE_DESTINATIONS, max_length=10)

    def is_available_for_rent(self):
        if self.use_destination == self.TO_CONSULT:
            return False

        copy_related_loans = self.loan_set.filter(book_copy=self)
        active_loans = [loan for loan in copy_related_loans if loan.is_active]

        if active_loans.__len__() == 0:
            return True
        return False

    def is_available_for_consultation_on(self, date):
        if self.use_destination == self.TO_RENT:
            return False

        copy_cons_reservation_on_given_date = ConsultationReservation.objects.filter(copy=self).filter(date=date)

        if copy_cons_reservation_on_given_date.count() == 0:
            return True
        return False

    def has_active_loan(self):
        try:
            loan_list = Loan.objects.filter(book_copy=self.id)
        except BaseException:
            loan_list = None

        active_loan = [loan for loan in loan_list if loan.is_active]
        return True if active_loan else False

    def has_rent_reservation(self):
        try:
            reservation = QueueOfRentReservations.objects.get(copy=self.id)
        except BaseException:
            reservation = None

        return True if reservation is not None else False

    def has_cons_reservation(self):
        try:
            rs = ConsultationReservation.objects.filter(copy=self.id)
        except BaseException:
            rs = None

        cons_reservation = [
            res for res in rs if res.date > datetime.now().date()]

        return True if cons_reservation else False

    def switch_use_destination(self):
        if self.use_destination == Copy.TO_CONSULT:
            self.use_destination = Copy.TO_RENT
        else:
            self.use_destination = Copy.TO_CONSULT

        self.save()


class ConsultationReservation(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    date = models.DateField(null=False)
    copy = models.ForeignKey(Copy, on_delete=models.CASCADE)
    user_is_using_the_copy = models.BooleanField(default=False)


class Loan(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    book_copy = models.ForeignKey(Copy, on_delete=models.CASCADE)
    inserted_on = models.DateField()

    started_on = models.DateField(null=True)
    finished_on = models.DateField(null=True)
    renewed_on = models.DateField(null=True)

    ready_for_withdraw = models.BooleanField(default=False)

    objects = LoanManager()

    @property
    def is_expired(self):

        if (
                self.is_started() and
                self.expiration_date() < datetime.now().date() and
                self.finished_on is None
        ):
            return True

        return False

    @property
    def is_active(self):
        return True if self.finished_on is None else False

    def is_expired_by(self):
        """returns the number of days the loan has expired or none instead"""

        if self.is_expired is False:
            return None

        delta = datetime.now().date() - self.started_on

        return delta.days - 30

    def is_started(self):
        return False if self.started_on is None else True

    @property
    def can_be_renewed(self):
        if not self.is_expired:
            return False

        if self.is_expired_by() < 5:
            return True
        else:
            return False

    def has_been_renewed(self):
        return True if not self.renewed_on else False

    def expiration_date(self):
        if self.started_on is None:
            return None
        if self.has_been_renewed():
            return self.started_on + timedelta(days=60)
        else:
            return self.started_on + timedelta(days=30)

    @property
    def completed(self):
        if self.finished_on is not None:
            return True

    def save(self, *args, **kwargs):
        if self.inserted_on is None:
            self.inserted_on = datetime.now().date()
        super(Loan, self).save(*args, **kwargs)


class StudyHallSeat(models.Model):

    def is_available_on(self, date):
        if StudyHallSeatReservation.objects.filter(
                seat=self.id, date=date).count() == 0:
            return True
        return False


class StudyHallSeatReservation(models.Model):
    seat = models.ForeignKey(StudyHallSeat, on_delete=models.CASCADE)
    date = models.DateField()
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    is_user_inside_study_hall = models.BooleanField(default=False)

    objects = StudyHallSeatReservationManager()

    # can't have multi-attribute primary key
    class Meta:
        unique_together = (("seat", "date", "user"),)



library_services/forms.py
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from django.forms import ModelForm, IntegerField, Form, CharField

from library_services.models import Book


class BuyBookForm(ModelForm):
    number_of_copies = IntegerField(min_value=1, max_value=10, label="Numero copie richieste")

    class Meta:
        model = Book
        fields = [
            'title',
            'author',
            'publishing_year',
            'language',
            'number_of_copies'
        ]
        labels = {
            # todo use translator ugettext
            'title': 'Titolo',
            'author': 'Autore',
            'publishing_year': 'Anno di Pubblicazione',
            'language': 'Lingua',
            'number_of_copies': 'Numero copie richieste'
        }


class AddCopiesForm(Form):
    number_of_rent_copies = IntegerField(
        min_value=0,
        label='Numero copie destinate al prestito',
        required=True,
        initial=0
    )
    number_of_cons_copies = IntegerField(
        min_value=0,
        label='Numero copie destinate alla consultazione',
        required=True,
        initial=0
    )

    class Meta:
        fields = '__all__'
        labels = {
            'number_of_rent_copies': 'Numero copie destinate al prestito',
            'number_of_cons_copies': 'Numero copie destinate alla consultazione'}


class AddBookForm(ModelForm):

    class Meta:
        model = Book
        fields = [
            'cover_img',
            'title',
            'author',
            'publishing_year',
            'language',
            'isbn'
        ]
        labels = {
            # todo use translator ugettext
            'cover_img': 'Url immagine di copertina',
            'title': 'Titolo',
            'author': 'Autore',
            'publishing_year': 'Anno di Pubblicazione',
            'language': 'Lingua',
            'isbn': 'Codice ISBN',
        }


class TurnstileForm(Form):
    badge_code = CharField(min_length=6, label="Codice badge")

    def __init__(self, *args, **kwargs):
        text = kwargs.pop('submit_button_text')

        self.helper = FormHelper()
        self.helper.add_input(Submit('submit', text, css_class='btn-outline-primary float-right'))
        self.helper.form_method = 'POST'

        super(TurnstileForm, self).__init__(*args, **kwargs)

library_services/templates/books/book_detail.html
{% extends 'base_navbar.html' %}

{% load static %}
{% load crispy_forms_tags %}

{% block css %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.0.0-alpha18/css/tempusdominus-bootstrap-4.min.css" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">
{% endblock %}

{% block right_content %}
    <div class="container">
        <div class="row">
            <div class="col-4">
                <img class="img-thumbnail" src="{{ book.cover_img }}">
            </div>

            <div class="col-8">

                <h1>
                    {{ book.title }}
                </h1>


                <table class="table">
                    <thead>
                    &nbsp;
                    </thead>
                    <tbody>
                    <tr>
                        <td>Autore:</td>
                        <td>{{ book.author }}</td>
                    </tr>
                    <tr>
                        <td>Edizione:</td>
                        <td>{{ book.publishing_year }}</td>
                    </tr>
                    <tr>
                        <td>ISBN:</td>
                        <td>{{ book.isbn}}</td>
                    </tr>
                    <tr>
                        <td>Lingua: </td>
                        <td>{{ book.get_language_display}}</td>
                    </tr>
                    </tbody>
                </table>

                <hr>
                &nbsp;

                {% if active_loan %}

                    <!-----------------------------USER HAS AN ACTIVE LOAN------------------------------------->
                    <div class="card table-bordered">
                        {% if active_loan.is_expired %}
                            <div class="card-body bg-light">
                                <div class="card-title">
                                    <h5 class="text-danger">Devi ancora riportare questo libro! Il prestito &egrave; scaduto da {{ active_loan.is_expired_by }} giorni!</h5>
                                    {% if active_loan.can_be_renewed %}
                                        <h5>Puoi rinnovare il prestito nella sezione<a href="{% url 'user-profile' %}">  prestiti in corso. </a></h5>
                                    {% endif %}

                                </div>
                            </div>
                        {% else %}

                            <div class="card-body bg-light">
                                <h5 class="card-title">Hai già un prestito attivo per questo libro</h5>
                                <ul>
                                    {% if not active_loan.started_on %}
                                        <li>Non hai ancora ritirato la copia. Ti ricordiamo che hai 7 giorni di tempo (da quando hai richiesto il prestito) per andare in biblioteca e ritirare la tua copia</li>
                                    {% else %}
                                        <li>Copia prelevata il: {{ active_loan.started_on }}</li>
                                        <li>Scade il: {{ active_loan.expiration_date }}</li>
                                    {% endif %}
                                </ul>
                            </div>

                        {% endif %}
                    </div>
                    <!-------------------------END | USER HAS AN ACTIVE LOAN------------------------------------->


                {% elif has_reservation%}

                    <!-----------------------------USER HAS AN ACTIVE LOAN RESERVATION------------------------->
                    <div class="card border-0">
                        <div class="card-title">
                            <div class="alert alert-danger" role="alert">
                                <h4>Hai già una prenotazione in coda per questo libro</h4>
                            </div>
                        </div>
                    </div>
                    <!-------------------------END | USER HAS AN ACTIVE LOAN RESERVATION------------------------->

                {% else %}

                    <!-----------------------------MAKE A LOAN RESERVATION--------------------------------------->
                    {% if book.has_at_least_one_rent_copy %}
                        {% if book.has_copy_available_for_rent %}
                            <div class="card table-bordered">
                                <div class="card-body bg-light">
                                    <div class="row">
                                        <div class="col-8">
                                            <h5 class="card-title text-success">Il libro è disponibile al prestito</h5>
                                        </div>
                                        <div class="col-4">
                                            <form method="post" action="">
                                                {% csrf_token %}
                                                <input type="hidden" name="action" value="insert_loan">
                                                <button type="submit" class="btn btn-success">
                                                    Richiedi prestito
                                                </button>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        {% else %}
                            <div class="card table-bordered">
                                <div class="card-body bg-light">
                                    <h5 class="card-title text-danger">Al momento non ci sono copie disponibili.</h5>
                                    <form method="post" action="">
                                        {% csrf_token %}
                                        <p class="card-text">Puoi effettuare una prenotazione. Non appena una copia tornerà disponibile ti avviseremo per mail e potrai ritirare il libro</p>
                                        <input type="hidden" name="action" value="insert_rent_reservation">
                                        <button type="submit" id="reservation" class="btn btn-warning">Prenota prestito</button>
                                    </form>
                                </div>
                            </div>
                        {% endif %}
                    {% elif book.has_at_least_one_cons_copy %}
                        <div class="card table-bordered">
                            <div class="card-body bg-light">
                                <h5 class="card-title text-warning">Questo libro è al momento disponibile solo per la consultazione in biblioteca</h5>
                            </div>
                        </div>
                    {% else %}
                        <div class="card table-bordered">
                            <div class="card-body bg-light">
                                <h5 class="card-title text-danger">Al momento la biblioteca non ha nessuna copia di questo libro</h5>
                            </div>
                        </div>
                    {% endif %}
                    <!-----------------------------END | MAKE A LOAN RESERVATION------------------------->

                {% endif %}


                {% if object.has_at_least_one_cons_copy and user.is_college_student %}
                    <hr>
                    <!-----------------------------MAKE A CONSULTATION RESERVATION------------------------->

                    <div class="card table-bordered">
                        <div class="card-body bg-light">
                            <div class="row">
                                <div class="col-8">
                                    <h5 class="card-title">Vuoi venire in biblioteca a studiare ma ti serve assolutamente questo volume? Prenotane una copia in consultazione! </h5>
                                </div>
                                <div class="col-4">
                                    <form method="post" action="">
                                        {% csrf_token %}
                                        <div class="form-group">
                                            <input type="hidden" name="action" value="insert_consultation_reservation"/>
                                            <div class="input-group date" id="datetimepicker4" data-target-input="nearest">
                                                <input type="text" name="date" class="form-control datetimepicker-input" data-target="#datetimepicker4"/>
                                                <div class="input-group-append" data-target="#datetimepicker4" data-toggle="datetimepicker">
                                                    <div class="input-group-text"><i class="fa fa-calendar"></i></div>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <button class="btn btn-success" type="submit" id="datetimepickerbtn">Prenota</button>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-------------------------END | MAKE A CONSULTATION RESERVATION------------------------->
                {% endif %}


            </div>
        </div>
    </div>
    </div>
{% endblock %}

{% block js %}
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.21.0/moment.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.0.0-alpha18/js/tempusdominus-bootstrap-4.min.js"></script>
    <script type="text/javascript" src="{% static 'js/book/detail.js' %}"></script>
{% endblock %}

library_services/templates/books/book_list.html
{% extends 'base_navbar.html'%}

{% block css %}
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">
{% endblock %}

{% block right_content %}

    <form action="{% url 'book-list' %}" method="get">
        <label class="col-form-label" for="searchbar"><h4>Ricerca per titolo o autore</h4></label>
        <div class="input-group">

            <input type="text" id="searchbar" name="q" placeholder="Cerca" class="form-control"/>
            <div class="input-group-append">
                <button class="btn btn-outline-secondary" type="submit">
                    <i class="fas fa-search"></i>
                </button>
            </div>
        </div>
    </form>

    {% if not object_list %}
        <h3 class=" text-center pt-5">
            La ricerca non ha prodotto nessun risultato
        </h3>
    {% else %}

        <table class="table pt-5">
        <thead>
        <tr>
            <th></th>
            <th>Titolo</th>
            <th>Autore</th>
            <th>Anno</th>
        </tr>
        </thead>
        <tbody>
        {% for book in object_list %}
            <tr>
                <td>
                    <img src="{{ book.cover_img }}" class="img-thumbnail" width="100" height="100">
                </td>
                <td>{{ book.title }} </td>
                <td>{{ book.author }} </td>
                <td>
                    {% if user.is_staff %}
                        <a href="{{ book.get_absolute_url }}/staff">
                    {% else %}
                        <a href="{{ book.get_absolute_url }}">
                    {% endif %}
                    <button class="btn"> dettagli </button>
                    </a>
                </td>
            </tr>
        {% endfor %}
    {% endif %}
</tbody>
</table>
{% endblock %}